$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: cfiar-dt-batch-deployment
endpoint_name: cfiar-endpoint-batch
model: 
  azureml:cifar_net.pt:5
code_configuration:
  code: ./data-science/src/
  scoring_script: batch_score.py
 
environment: azureml:AzureML-pytorch-1.9-ubuntu18.04-py37-cuda11.0.3-gpu-inference:1
compute: azureml:gpu-cluster
resources:
  instance_count: 1
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1
logging_level: info
